import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar.tsx";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zenchi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}     bg-[#070B0C] antialiased `}>
        <header className="!fixed left-0 top-0 w-full flex items-center h-[93px] justify-center  backdrop-blur-lg  px-[6vw] z-50 ">
          {" "}
          <Navbar />
        </header>

        {children}
      </body>
    </html>
  );
}
